### ISSUE TITLE
Ошибка 500

### ISSUE THREAD

**Issue by ilyamio** [liquetsoft/cbrfservice#19]
@marvin255 @liquetsoft  При использовании скрипта, страницы отдают ошибку 500.
Я использовал скрипт без интеграции в cms. Может [cbrfservice](https://github.com/liquetsoft/cbrfservice) работает с каким-либо конкретным cms или cmf?

**Comment by ilyamio** [comment]
@marvin255 @liquetsoft Здравствуйте. Можете ответить на предыдущий комментарий? Спасибо!

**Comment by liquetsoft** [comment]
Добрый день.
Каких-либо CMS бандлов нет.
Если бы вы могли предоставить стэк трэйс или хотя бы описание ошибки, это бы помогло в диагностировании проблемы.

**Comment by liquetsoft** [comment]
Каких-то ошибок не наблюдается, кроме пустых ответов. Можете попробовать эту https://github.com/liquetsoft/cbrfservice/releases/tag/v5.0.1 версию.

**Comment by ilyamio** [comment]
> Добрый день. Каких-либо CMS бандлов нет. Если бы вы могли предоставить стэк трэйс или хотя бы описание ошибки, это бы помогло в диагностировании проблемы.

Здравствуйте.
Спасибо, что написали.
При открытии страницы http://site,ru/vendor/liquetsoft/cbrfservice/tests/CbrfSoapServiceTest.php
выходит такая ошибка:
Fatal error: Uncaught Error: Class 'Liquetsoft\CbrfService\Tests\BaseTestCase' not found in /home/site,ru/public_html/vendor/liquetsoft/cbrfservice/tests/CbrfSoapServiceTest.php:16 Stack trace: #0 {main} thrown in /home/site,ru/public_html/vendor/liquetsoft/cbrfservice/tests/CbrfSoapServiceTest.php on line 16

Папки и файлы расположены следующим образом: https://skr.sh/vEr2Q9Ay8UM?a

**Comment by ilyamio** [comment]
> Каких-то ошибок не наблюдается, кроме пустых ответов. Можете попробовать эту https://github.com/liquetsoft/cbrfservice/releases/tag/v5.0.1 версию.

После установки этой версии, возникли такие ошибки:
Fatal error: Uncaught SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?WSDL' : failed to load external entity "http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?WSDL" in /home/site.ru/public_html/vendor/liquetsoft/cbrfservice/src/CbrfSoapService.php:122 Stack trace: #0 /home/site.ru/public_html/vendor/liquetsoft/cbrfservice/src/CbrfSoapService.php(122): SoapClient->SoapClient('http://www.cbr....', Array) #1 /home/site.ru/public_html/vendor/liquetsoft/cbrfservice/src/CbrfSoapService.php(68): Liquetsoft\CbrfService\CbrfSoapService->getSoapClient() #2 /home/site.ru/public_html/vendor/liquetsoft/cbrfservice/src/CbrfSoapService.php(46): Liquetsoft\CbrfService\CbrfSoapService->queryInternal('GetCursOnDate', Array) #3 /home/site.ru/public_html/vendor/liquetsoft/cbrfservice/src/CbrfDaily.php(48): Liquetsoft\CbrfService\CbrfSoapService->query('GetCursOnDate', in /home/site.ru/public_html/vendor/liquetsoft/cbrfservice/src/CbrfSoapService.php on line 49

**Comment by ilyamio** [comment]
Добрый день, @liquetsoft 
Как связаться с вами? Не нашел ваши контакты. Вы можете написать мне на @IlyaMuradzade или написать ваш телеграмм? Спасибо!

**Comment by ilyamio** [comment]
> > отображается только белый экран
> 
> Не могли бы вы поискать логи, в которых явно указана ошибка? Например [php error log](https://stackoverflow.com/questions/5127838/where-does-php-store-the-error-log-php-5-apache-fastcgi-and-cpanel). Диагностика библиотеки никаких проблем не выявила.

Добрый день! В логах ошибок нет. Только белый экран. Версия 5.0.1. Запускаю скрипт следующим образом: site.ru/kursy.php https://skr.sh/vEsNqkmVyZf?a

**Comment by ilyamio** [comment]
> > Добрый день! В логах ошибок нет. Только белый экран. Версия 5.0.1. Запускаю скрипт следующим образом: site.ru/kursy.php https://skr.sh/vEsNqkmVyZf?a
> 
> В таком случае есть смысл предполагать, что ошибок нет. Метод, который был использован (как и все методы библиотеки), ничего не выводит в output, поэтому ничего и не отображается. `keyRate` вернет массив объектов со ставками и все. Как его перебрать и что именно отобразить - задача уже клиентского скрипта. Для того, чтобы убедиться, попробуйте
> 
> ```
> // composer include and objects init here
> $keyRate = $cbrf->keyRate(
>     new \DateTimeImmutable('-1 month'),
>     new \DateTimeImmutable()
> );
> var_dump($keyRate);
> ```

Предполагаю, результат должен быть таким: https://skr.sh/sEsGuzP7k7B?a верно?
@liquetsoft и еще раз хотел спросить, как с вами связаться? у меня к вам предложение.

**Comment by liquetsoft** [comment]
> Предполагаю, результат должен быть таким: https://skr.sh/sEsGuzP7k7B?a верно?

Да, именно так.

>  и еще раз хотел спросить, как с вами связаться? 

К сожалению, сейчас это невозможно.
